"@domain/environment":
  - nested/environments/**
"@domain/layer":
  - nested/layers/**
"@domain/module":
  - nested/modules/**
"@domain/manual":
  - flat/manual/**
"@domain/modular":
  - flat/modular/**
"@type/gitops":
  - .github/**